# hexband.R — emit _hexband.qmd (a raw-HTML include used by hexband.qmd and the CV): an irregular, bunched honeycomb band that runs
# down the right-hand edge of the viewport (layout demo, companion to hexwall.qmd).
#
# Hexes stay on a point-up lattice so neighbours nest; irregularity comes from
# which cells are filled. Fill probability decays with distance from the right
# edge and is boosted when the two cells above are filled, so occupancy clumps.
# Positions are emitted as lattice coordinates (--c, --r) and resolved in CSS.

set.seed(20260902)

stickers <- c(research = "Research hex sticker",
              projects = "Projects hex sticker",
              `left-hand-thoughts` = "Left-hand Thoughts hex sticker",
              # round 2 (2026-09-05): Peter's puzzled face + one mark per career phase
              puzzled = "Puzzled Peter hex sticker",
              criminology = "Criminology hex sticker: a pair of heavy iron handcuffs lying on a wooden table, one small iron key beside them and a lit candle behind",
              genomics = "Genomics hex sticker",
              responders = "First responder hex sticker: a bronze tri-service challenge coin standing on edge on a stone ledge, a lit candle beside it")

n_rows <- 22          # enough to cover a tall viewport; container clips the rest
n_cols <- 3           # col 1 is flush right (half off-screen on shifted rows)
p_base <- c(0.72, 0.38, 0.14)

# --- occupancy: which lattice cells hold a hex at all (all ink by default) ---
filled <- matrix(FALSE, n_rows, n_cols)
for (r in seq_len(n_rows)) {
  for (c in seq_len(n_cols)) {
    above <- if (r > 1) mean(filled[r - 1, max(1, c - 1):min(n_cols, c + 1)]) else 0
    p <- min(0.90, p_base[c] + 0.30 * above - 0.15 * (above == 0 & c > 1))
    filled[r, c] <- runif(1) < p
  }
}

# lattice x-offset in hex widths from the right edge; shifted rows sit half a
# cell further out, so their first column is half off-screen
col_of <- function(r, c) (c - 1) - ifelse(r %% 2 == 0, 0.5, 0)

# --- allocation: every art sticker goes to a fully visible cell -------------
# Eligible = filled, not the half-off-screen edge column, not the outer column
# (clipped by the band's width / gutter fade), and within the rows a typical
# viewport shows below the navbar (rows 3-14 since the band grew to seven
# art stickers). Sampled without replacement; as more
# stickers are made, add them to `stickers` and they get allocated too.
eligible <- which(filled & outer(seq_len(n_rows), seq_len(n_cols), col_of) >= 0 &
                  col(filled) <= 2 & row(filled) %in% 3:14, arr.ind = TRUE)
stopifnot(nrow(eligible) >= length(stickers))
# Spread down the band: draw one cell at a time and exclude cells within
# `min_gap` rows of it, so no two stickers sit adjacent. If the band runs out
# of room before every sticker is placed, relax the gap by one and continue.
n_pick  <- length(stickers)
min_gap <- 3
idx     <- integer(0)
repeat {
  avail <- setdiff(seq_len(nrow(eligible)), idx)
  if (length(idx)) avail <- avail[sapply(avail, function(i)
    all(abs(eligible[i, "row"] - eligible[idx, "row"]) >= min_gap))]
  if (length(idx) == n_pick) break
  if (!length(avail)) { min_gap <- min_gap - 1; stopifnot(min_gap >= 1); next }
  idx <- c(idx, if (length(avail) == 1) avail else sample(avail, 1))
}
pick <- eligible[idx, , drop = FALSE]
key  <- matrix(NA_character_, n_rows, n_cols)
key[pick] <- sample(names(stickers))

tags <- character()
for (r in seq_len(n_rows)) for (c in seq_len(n_cols)) if (filled[r, c]) {
  k   <- if (is.na(key[r, c])) "blank" else key[r, c]
  alt <- if (k == "blank") "" else stickers[[k]]
  tags <- c(tags, sprintf(
    '<img src="/www/hex/%s.png" alt="%s" style="--c:%s;--r:%d">', k, alt, col_of(r, c), r - 1))
}

body <- c(
  "<!-- generated by 4_stickers/hexband.R; do not edit by hand -->",
  "```{=html}",
  '<div class="hexband" aria-hidden="true">',
  tags,
  "</div>",
  "```"
)
writeLines(body, "_hexband.qmd")
cat(sprintf("_hexband.qmd written: %d hexes over %d rows (%.0f%% fill); %d art stickers placed among %d eligible cells\n",
            sum(filled), n_rows, 100 * mean(filled), nrow(pick), nrow(eligible)))
